# Generated by Django 3.2.12 on 2023-02-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configure', '0004_difficulty_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('current_game_score', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members_on_team', to=settings.AUTH_USER_MODEL)),
                ('temporarily_banned_categories', models.ManyToManyField(related_name='temporarily_banned_team_categories', to='configure.Category')),
                ('temporarily_banned_difficulties', models.ManyToManyField(related_name='temporarily_banned_team_difficulties', to='configure.Difficulty')),
                ('temporarily_banned_eras', models.ManyToManyField(related_name='temporarily_banned_team_eras', to='configure.Era')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('time_per_question', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned_categories', models.ManyToManyField(related_name='banned_game_categories', to='configure.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(related_name='games', to='compete.Team')),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
    ]
