# Generated by Django 3.2.12 on 2023-02-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_game_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
