# Generated by Django 3.2.12 on 2023-02-27 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compete', '0003_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='all_users',
            field=models.ManyToManyField(related_name='all_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='teams_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(max_length=64),
        ),
    ]
