# Generated by Django 3.2.12 on 2023-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='era',
        ),
        migrations.AddField(
            model_name='question',
            name='eras',
            field=models.ManyToManyField(related_name='questions_for_era', to='configure.Era'),
        ),
    ]
